<a href="https://colab.research.google.com/github/ggalarza1/stock_financials/blob/main/Stk_financials.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Fetching stocks historicals
(Income Statement, Balance Sheet, Cashflows, Dividends and also the SEC Filings the yahoo API has)

#Calling the Income Statement (Yearly/Quaterly)

In [3]:
#Calling Ticker Income Statement Quarterly Financials
import yfinance as yf

income_statement = yf.Ticker("aapl").quarterly_financials
income_statement

,2024-09-30,2024-06-30,2024-03-31,2023-12-31,2023-09-30,2023-06-30
Tax Effect Of Unusual Items,0.0,0.0,0.0,0.0,0.0,NaN
Tax Rate For Calcs,0.21,0.159,0.158,0.159,0.149715,NaN
Normalized EBITDA,32502000000.0,28202000000.0,30736000000.0,43221000000.0,30653000000.0,NaN
Net Income From Continuing Operation Net Minority Interest,14736000000.0,21448000000.0,23636000000.0,33916000000.0,22956000000.0,NaN
Reconciled Depreciation,2911000000.0,2850000000.0,2836000000.0,2848000000.0,2653000000.0,NaN
Reconciled Cost Of Revenue,51051000000.0,46099000000.0,48482000000.0,64720000000.0,49071000000.0,NaN
EBITDA,32502000000.0,28202000000.0,30736000000.0,43221000000.0,30653000000.0,NaN
EBIT,29591000000.0,25352000000.0,27900000000.0,40373000000.0,28000000000.0,NaN
Net Interest Income,NaN,NaN,NaN,NaN,-18000000.0,-18000000.0
Interest Expense,NaN,NaN,NaN,NaN,1002000000.0,998000000.0
Interest Income,NaN,NaN,NaN,NaN,984000000.0,980000000.0
Normalized Income,14736000000.0,21448000000.0,23636000000.0,33916000000.0,22956000000.0,NaN
Net Income From Continuing And Discontinued Operation,14736000000.0,21448000000.0,23636000000.0,33916000000.0,22956000000.0,NaN
Total Expenses,65339000000.0,60425000000.0,62853000000.0,79202000000.0,62529000000.0,NaN
Total Operating Income As Reported,29591000000.0,25352000000.0,27900000000.0,40373000000.0,26969000000.0,NaN
Diluted Average Shares,15242853000.0,15348175000.0,15464709000.0,15576641000.0,15672400000.0,NaN
Basic Average Shares,15171990000.0,15287521000.0,15405856000.0,15509763000.0,15599434000.0,NaN
Diluted EPS,0.97,1.4,1.53,2.18,1.46,NaN
Basic EPS,0.97,1.4,1.53,2.19,1.47,NaN
Diluted NI Availto Com Stockholders,14736000000.0,21448000000.0,23636000000.0,33916000000.0,22956000000.0,NaN
Net Income Common Stockholders,14736000000.0,21448000000.0,23636000000.0,33916000000.0,22956000000.0,NaN
Net Income,14736000000.0,21448000000.0,23636000000.0,33916000000.0,22956000000.0,NaN
Net Income Including Noncontrolling Interests,14736000000.0,21448000000.0,23636000000.0,33916000000.0,22956000000.0,NaN
Net Income Continuous Operations,14736000000.0,21448000000.0,23636000000.0,33916000000.0,22956000000.0,NaN
Tax Provision,14874000000.0,4046000000.0,4422000000.0,6407000000.0,4042000000.0,NaN
Pretax Income,29610000000.0,25494000000.0,28058000000.0,40323000000.0,26998000000.0,NaN
Other Income Expense,19000000.0,142000000.0,158000000.0,-50000000.0,47000000.0,NaN
Other Non Operating Income Expenses,19000000.0,142000000.0,158000000.0,-50000000.0,47000000.0,NaN
Net Non Operating Interest Income Expense,NaN,NaN,NaN,NaN,-18000000.0,-18000000.0
Interest Expense Non Operating,NaN,NaN,NaN,NaN,1002000000.0,998000000.0
Interest Income Non Operating,NaN,NaN,NaN,NaN,984000000.0,980000000.0
Operating Income,29591000000.0,25352000000.0,27900000000.0,40373000000.0,26969000000.0,NaN
Operating Expense,14288000000.0,14326000000.0,14371000000.0,14482000000.0,13458000000.0,NaN
Research And Development,7765000000.0,8006000000.0,7903000000.0,7696000000.0,7307000000.0,NaN
Selling General And Administration,6523000000.0,6320000000.0,6468000000.0,6786000000.0,6151000000.0,NaN
Gross Profit,43879000000.0,39678000000.0,42271000000.0,54855000000.0,40427000000.0,NaN
Cost Of Revenue,51051000000.0,46099000000.0,48482000000.0,64720000000.0,49071000000.0,NaN
Total Revenue,94930000000.0,85777000000.0,90753000000.0,119575000000.0,89498000000.0,NaN
Operating Revenue,94930000000.0,85777000000.0,90753000000.0,119575000000.0,89498000000.0,NaN

In [6]:
#Calling Ticker Income Statement Yearly Financials
import yfinance as yf

income_statement = yf.Ticker("aapl").financials
income_statement

,2024-09-30,2023-09-30,2022-09-30,2021-09-30,2020-09-30
Tax Effect Of Unusual Items,0.0,0.0,0.0,0.0,NaN
Tax Rate For Calcs,0.240912,0.147192,0.162,0.133,NaN
Normalized EBITDA,134661000000.0,125820000000.0,130541000000.0,123136000000.0,NaN
Net Income From Continuing Operation Net Minority Interest,93736000000.0,96995000000.0,99803000000.0,94680000000.0,NaN
Reconciled Depreciation,11445000000.0,11519000000.0,11104000000.0,11284000000.0,NaN
Reconciled Cost Of Revenue,210352000000.0,214137000000.0,223546000000.0,212981000000.0,NaN
EBITDA,134661000000.0,125820000000.0,130541000000.0,123136000000.0,NaN
EBIT,123216000000.0,114301000000.0,119437000000.0,111852000000.0,NaN
Net Interest Income,NaN,-183000000.0,-106000000.0,198000000.0,890000000.0
Interest Expense,NaN,3933000000.0,2931000000.0,2645000000.0,2873000000.0
Interest Income,NaN,3750000000.0,2825000000.0,2843000000.0,3763000000.0
Normalized Income,93736000000.0,96995000000.0,99803000000.0,94680000000.0,NaN
Net Income From Continuing And Discontinued Operation,93736000000.0,96995000000.0,99803000000.0,94680000000.0,NaN
Total Expenses,267819000000.0,268984000000.0,274891000000.0,256868000000.0,NaN
Total Operating Income As Reported,123216000000.0,114301000000.0,119437000000.0,108949000000.0,NaN
Diluted Average Shares,NaN,15812547000.0,16325819000.0,16864919000.0,17528214000.0
Basic Average Shares,NaN,15744231000.0,16215963000.0,16701272000.0,17352119000.0
Diluted EPS,NaN,6.13,6.11,5.61,3.28
Basic EPS,NaN,6.16,6.15,5.67,3.31
Diluted NI Availto Com Stockholders,93736000000.0,96995000000.0,99803000000.0,94680000000.0,NaN
Net Income Common Stockholders,93736000000.0,96995000000.0,99803000000.0,94680000000.0,NaN
Net Income,93736000000.0,96995000000.0,99803000000.0,94680000000.0,NaN
Net Income Including Noncontrolling Interests,93736000000.0,96995000000.0,99803000000.0,94680000000.0,NaN
Net Income Continuous Operations,93736000000.0,96995000000.0,99803000000.0,94680000000.0,NaN
Tax Provision,29749000000.0,16741000000.0,19300000000.0,14527000000.0,NaN
Pretax Income,123485000000.0,113736000000.0,119103000000.0,109207000000.0,NaN
Other Income Expense,269000000.0,-565000000.0,-334000000.0,60000000.0,NaN
Other Non Operating Income Expenses,269000000.0,-565000000.0,-334000000.0,60000000.0,NaN
Net Non Operating Interest Income Expense,NaN,-183000000.0,-106000000.0,198000000.0,890000000.0
Interest Expense Non Operating,NaN,3933000000.0,2931000000.0,2645000000.0,2873000000.0
Interest Income Non Operating,NaN,3750000000.0,2825000000.0,2843000000.0,3763000000.0
Operating Income,123216000000.0,114301000000.0,119437000000.0,108949000000.0,NaN
Operating Expense,57467000000.0,54847000000.0,51345000000.0,43887000000.0,NaN
Research And Development,31370000000.0,29915000000.0,26251000000.0,21914000000.0,NaN
Selling General And Administration,26097000000.0,24932000000.0,25094000000.0,21973000000.0,NaN
Gross Profit,180683000000.0,169148000000.0,170782000000.0,152836000000.0,NaN
Cost Of Revenue,210352000000.0,214137000000.0,223546000000.0,212981000000.0,NaN
Total Revenue,391035000000.0,383285000000.0,394328000000.0,365817000000.0,NaN
Operating Revenue,391035000000.0,383285000000.0,394328000000.0,365817000000.0,NaN

In [12]:
# You can also call the Income statement using the income_stmt
income = yf.Ticker("aapl").income_stmt
income

,2024-09-30,2023-09-30,2022-09-30,2021-09-30,2020-09-30
Tax Effect Of Unusual Items,0.0,0.0,0.0,0.0,NaN
Tax Rate For Calcs,0.240912,0.147192,0.162,0.133,NaN
Normalized EBITDA,134661000000.0,125820000000.0,130541000000.0,123136000000.0,NaN
Net Income From Continuing Operation Net Minority Interest,93736000000.0,96995000000.0,99803000000.0,94680000000.0,NaN
Reconciled Depreciation,11445000000.0,11519000000.0,11104000000.0,11284000000.0,NaN
Reconciled Cost Of Revenue,210352000000.0,214137000000.0,223546000000.0,212981000000.0,NaN
EBITDA,134661000000.0,125820000000.0,130541000000.0,123136000000.0,NaN
EBIT,123216000000.0,114301000000.0,119437000000.0,111852000000.0,NaN
Net Interest Income,NaN,-183000000.0,-106000000.0,198000000.0,890000000.0
Interest Expense,NaN,3933000000.0,2931000000.0,2645000000.0,2873000000.0
Interest Income,NaN,3750000000.0,2825000000.0,2843000000.0,3763000000.0
Normalized Income,93736000000.0,96995000000.0,99803000000.0,94680000000.0,NaN
Net Income From Continuing And Discontinued Operation,93736000000.0,96995000000.0,99803000000.0,94680000000.0,NaN
Total Expenses,267819000000.0,268984000000.0,274891000000.0,256868000000.0,NaN
Total Operating Income As Reported,123216000000.0,114301000000.0,119437000000.0,108949000000.0,NaN
Diluted Average Shares,NaN,15812547000.0,16325819000.0,16864919000.0,17528214000.0
Basic Average Shares,NaN,15744231000.0,16215963000.0,16701272000.0,17352119000.0
Diluted EPS,NaN,6.13,6.11,5.61,3.28
Basic EPS,NaN,6.16,6.15,5.67,3.31
Diluted NI Availto Com Stockholders,93736000000.0,96995000000.0,99803000000.0,94680000000.0,NaN
Net Income Common Stockholders,93736000000.0,96995000000.0,99803000000.0,94680000000.0,NaN
Net Income,93736000000.0,96995000000.0,99803000000.0,94680000000.0,NaN
Net Income Including Noncontrolling Interests,93736000000.0,96995000000.0,99803000000.0,94680000000.0,NaN
Net Income Continuous Operations,93736000000.0,96995000000.0,99803000000.0,94680000000.0,NaN
Tax Provision,29749000000.0,16741000000.0,19300000000.0,14527000000.0,NaN
Pretax Income,123485000000.0,113736000000.0,119103000000.0,109207000000.0,NaN
Other Income Expense,269000000.0,-565000000.0,-334000000.0,60000000.0,NaN
Other Non Operating Income Expenses,269000000.0,-565000000.0,-334000000.0,60000000.0,NaN
Net Non Operating Interest Income Expense,NaN,-183000000.0,-106000000.0,198000000.0,890000000.0
Interest Expense Non Operating,NaN,3933000000.0,2931000000.0,2645000000.0,2873000000.0
Interest Income Non Operating,NaN,3750000000.0,2825000000.0,2843000000.0,3763000000.0
Operating Income,123216000000.0,114301000000.0,119437000000.0,108949000000.0,NaN
Operating Expense,57467000000.0,54847000000.0,51345000000.0,43887000000.0,NaN
Research And Development,31370000000.0,29915000000.0,26251000000.0,21914000000.0,NaN
Selling General And Administration,26097000000.0,24932000000.0,25094000000.0,21973000000.0,NaN
Gross Profit,180683000000.0,169148000000.0,170782000000.0,152836000000.0,NaN
Cost Of Revenue,210352000000.0,214137000000.0,223546000000.0,212981000000.0,NaN
Total Revenue,391035000000.0,383285000000.0,394328000000.0,365817000000.0,NaN
Operating Revenue,391035000000.0,383285000000.0,394328000000.0,365817000000.0,NaN

#Getting the Balance Sheet (Yearly/Quaterly)

In [3]:
#If you call balance sheet, It will give you the results yearly.
import yfinance as yf

balancesheet_statement = yf.Ticker("aapl").balance_sheet
balancesheet_statement

,2024-09-30,2023-09-30,2022-09-30,2021-09-30,2020-09-30
Treasury Shares Number,NaN,0.0,NaN,NaN,NaN
Ordinary Shares Number,15116786000.0,15550061000.0,15943425000.0,16426786000.0,NaN
Share Issued,15116786000.0,15550061000.0,15943425000.0,16426786000.0,NaN
Net Debt,76686000000.0,81123000000.0,96423000000.0,89779000000.0,NaN
Total Debt,106629000000.0,111088000000.0,132480000000.0,136522000000.0,NaN
...,...,...,...,...,...
Cash Cash Equivalents And Short Term Investments,65171000000.0,61555000000.0,48304000000.0,62639000000.0,NaN
Other Short Term Investments,35228000000.0,31590000000.0,24658000000.0,27699000000.0,NaN
Cash And Cash Equivalents,29943000000.0,29965000000.0,23646000000.0,34940000000.0,NaN
Cash Equivalents,2744000000.0,1606000000.0,5100000000.0,17635000000.0,NaN
Cash Financial,27199000000.0,28359000000.0,18546000000.0,17305000000.0,NaN

In [7]:
#Calling the quarterly balance sheet
balancesheet_statement = yf.Ticker("aapl").quarterly_balance_sheet
balancesheet_statement

,2024-09-30,2024-06-30,2024-03-31,2023-12-31,2023-09-30,2023-06-30
Treasury Shares Number,NaN,NaN,NaN,0.0,0.0,NaN
Ordinary Shares Number,15116786000.0,15222259000.0,15337686000.0,15460223000.0,15550061000.0,NaN
Share Issued,15116786000.0,15222259000.0,15337686000.0,15460223000.0,15550061000.0,NaN
Net Debt,76686000000.0,75739000000.0,71895000000.0,67280000000.0,81123000000.0,NaN
Total Debt,106629000000.0,101304000000.0,104590000000.0,108040000000.0,111088000000.0,NaN
...,...,...,...,...,...,...
Cash Cash Equivalents And Short Term Investments,65171000000.0,61801000000.0,67150000000.0,73100000000.0,61555000000.0,NaN
Other Short Term Investments,35228000000.0,36236000000.0,34455000000.0,32340000000.0,31590000000.0,NaN
Cash And Cash Equivalents,29943000000.0,25565000000.0,32695000000.0,40760000000.0,29965000000.0,NaN
Cash Equivalents,2744000000.0,2699000000.0,4468000000.0,11218000000.0,1606000000.0,NaN
Cash Financial,27199000000.0,22866000000.0,28227000000.0,29542000000.0,28359000000.0,NaN

#Getting the Cashflow (Yearly/Quaterly)

In [5]:
# Calling cashflow gives you the result yearly
cashflow = yf.Ticker("aapl").cashflow
cashflow

,2024-09-30,2023-09-30,2022-09-30,2021-09-30,2020-09-30
Free Cash Flow,108807000000.0,99584000000.0,111443000000.0,92953000000.0,NaN
Repurchase Of Capital Stock,-94949000000.0,-77550000000.0,-89402000000.0,-85971000000.0,NaN
Repayment Of Debt,-9958000000.0,-11151000000.0,-9543000000.0,-8750000000.0,NaN
Issuance Of Debt,0.0,5228000000.0,5465000000.0,20393000000.0,NaN
Issuance Of Capital Stock,NaN,NaN,NaN,1105000000.0,880000000.0
Capital Expenditure,-9447000000.0,-10959000000.0,-10708000000.0,-11085000000.0,NaN
Interest Paid Supplemental Data,NaN,3803000000.0,2865000000.0,2687000000.0,3002000000.0
Income Tax Paid Supplemental Data,26102000000.0,18679000000.0,19573000000.0,25385000000.0,NaN
End Cash Position,29943000000.0,30737000000.0,24977000000.0,35929000000.0,NaN
Beginning Cash Position,30737000000.0,24977000000.0,35929000000.0,39789000000.0,NaN
Changes In Cash,-794000000.0,5760000000.0,-10952000000.0,-3860000000.0,NaN
Financing Cash Flow,-121983000000.0,-108488000000.0,-110749000000.0,-93353000000.0,NaN
Cash Flow From Continuing Financing Activities,-121983000000.0,-108488000000.0,-110749000000.0,-93353000000.0,NaN
Net Other Financing Charges,-5802000000.0,-6012000000.0,-6383000000.0,-5580000000.0,NaN
Cash Dividends Paid,-15234000000.0,-15025000000.0,-14841000000.0,-14467000000.0,NaN
Common Stock Dividend Paid,-15234000000.0,-15025000000.0,-14841000000.0,-14467000000.0,NaN
Net Common Stock Issuance,-94949000000.0,-77550000000.0,-89402000000.0,-85971000000.0,NaN
Common Stock Payments,-94949000000.0,-77550000000.0,-89402000000.0,-85971000000.0,NaN
Common Stock Issuance,NaN,NaN,NaN,1105000000.0,880000000.0
Net Issuance Payments Of Debt,-5998000000.0,-9901000000.0,-123000000.0,12665000000.0,NaN
Net Short Term Debt Issuance,3960000000.0,-3978000000.0,3955000000.0,1022000000.0,NaN
Net Long Term Debt Issuance,-9958000000.0,-5923000000.0,-4078000000.0,11643000000.0,NaN
Long Term Debt Payments,-9958000000.0,-11151000000.0,-9543000000.0,-8750000000.0,NaN
Long Term Debt Issuance,0.0,5228000000.0,5465000000.0,20393000000.0,NaN
Investing Cash Flow,2935000000.0,3705000000.0,-22354000000.0,-14545000000.0,NaN
Cash Flow From Continuing Investing Activities,2935000000.0,3705000000.0,-22354000000.0,-14545000000.0,NaN
Net Other Investing Changes,-1308000000.0,-1337000000.0,-2086000000.0,-385000000.0,NaN
Net Investment Purchase And Sale,13690000000.0,16001000000.0,-9560000000.0,-3075000000.0,NaN
Sale Of Investment,62346000000.0,45514000000.0,67363000000.0,106483000000.0,NaN
Purchase Of Investment,-48656000000.0,-29513000000.0,-76923000000.0,-109558000000.0,NaN
Net Business Purchase And Sale,NaN,NaN,-306000000.0,-33000000.0,-1524000000.0
Purchase Of Business,NaN,NaN,-306000000.0,-33000000.0,-1524000000.0
Net PPE Purchase And Sale,-9447000000.0,-10959000000.0,-10708000000.0,-11085000000.0,NaN
Purchase Of PPE,-9447000000.0,-10959000000.0,-10708000000.0,-11085000000.0,NaN
Operating Cash Flow,118254000000.0,110543000000.0,122151000000.0,104038000000.0,NaN
Cash Flow From Continuing Operating Activities,118254000000.0,110543000000.0,122151000000.0,104038000000.0,NaN
Change In Working Capital,3651000000.0,-6577000000.0,1200000000.0,-4911000000.0,NaN
Change In Other Working Capital,NaN,NaN,478000000.0,1676000000.0,2081000000.0
Change In Other Current Liabilities,15552000000.0,3031000000.0,6110000000.0,7475000000.0,NaN
Change In Other Current Assets,-11731000000.0,-5684000000.0,-6499000000.0,-8042000000.0,NaN
Change In Payables And Accrued Expense,6020000000.0,-1889000000.0,9448000000.0,12326000000.0,NaN
Change In Payable,6020000000.0,-1889000000.0,9448000000.0,12326000000.0,NaN
Change In Account Payable,6020000000.0,-1889000000.0,9448000000.0,12326000000.0,NaN
Change In Inventory,-1046000000.0,-1618000000.0,1484000000.0,-2642000000.0,NaN
Change In Receivables,-5144000000.0,-417000000.0,-9343000000.0,-14028000000.0,NaN
Changes In Account Receivables,-3788000000.0,-1688000000.0,-1823000000.0,-10125000000.0,NaN
Other Non Cash Items,-2266000000.0,-2227000000.0,1006000000.0,-4921000000.0,NaN
Stock Based Compensation,11688000000.0,10833000000.0,9038000000.0,7906000000.0,NaN
Deferred Tax,NaN,NaN,895000000.0,-4774000000.0,-215000000.0
Deferred Income Tax,NaN,NaN,895000000.0,-4774000000.0,-215000000.0
Depreciation Amortization Depletion,11445000000.0,11519000000.0,11104000000.0,11284000000.0,NaN
Depreciation And Amortization,11445000000.0,11519000000.0,11104000000.0,11284000000.0,NaN
Net Income From Continuing Operations,93736000000.0,96995000000.0,99803000000.0,94680000000.0,NaN

In [8]:
# Calling cashflow gives you the result yearly
cashflow = yf.Ticker("aapl").quarterly_cashflow
cashflow

,2024-09-30,2024-06-30,2024-03-31,2023-12-31,2023-09-30,2023-06-30
Free Cash Flow,23903000000.0,26707000000.0,20694000000.0,37503000000.0,19435000000.0,NaN
Repurchase Of Capital Stock,-25083000000.0,-26522000000.0,-23205000000.0,-20139000000.0,-21003000000.0,NaN
Repayment Of Debt,427000000.0,-3253000000.0,-3148000000.0,-3984000000.0,0.0,NaN
Issuance Of Debt,0.0,NaN,NaN,NaN,0.0,NaN
Capital Expenditure,-2908000000.0,-2151000000.0,-1996000000.0,-2392000000.0,-2163000000.0,NaN
Interest Paid Supplemental Data,NaN,NaN,NaN,NaN,1213000000.0,717000000.0
Income Tax Paid Supplemental Data,6872000000.0,4699000000.0,7276000000.0,7255000000.0,11659000000.0,NaN
End Cash Position,29943000000.0,26635000000.0,33921000000.0,41974000000.0,30737000000.0,NaN
Beginning Cash Position,26635000000.0,33921000000.0,41974000000.0,30737000000.0,29898000000.0,NaN
Changes In Cash,3308000000.0,-7286000000.0,-8053000000.0,11237000000.0,839000000.0,NaN
Financing Cash Flow,-24948000000.0,-36017000000.0,-30433000000.0,-30585000000.0,-23153000000.0,NaN
Cash Flow From Continuing Financing Activities,-24948000000.0,-36017000000.0,-30433000000.0,-30585000000.0,-23153000000.0,NaN
Net Other Financing Charges,-448000000.0,-2347000000.0,-370000000.0,-2637000000.0,-385000000.0,NaN
Cash Dividends Paid,-3804000000.0,-3895000000.0,-3710000000.0,-3825000000.0,-3758000000.0,NaN
Common Stock Dividend Paid,-3804000000.0,-3895000000.0,-3710000000.0,-3825000000.0,-3758000000.0,NaN
Net Common Stock Issuance,-25083000000.0,-26522000000.0,-23205000000.0,-20139000000.0,-21003000000.0,NaN
Common Stock Payments,-25083000000.0,-26522000000.0,-23205000000.0,-20139000000.0,-21003000000.0,NaN
Net Issuance Payments Of Debt,4387000000.0,-3253000000.0,-3148000000.0,-3984000000.0,1993000000.0,NaN
Net Short Term Debt Issuance,6945000000.0,997000000.0,2000000.0,-3984000000.0,1993000000.0,NaN
Short Term Debt Payments,NaN,997000000.0,2000000.0,-3984000000.0,NaN,1989000000.0
Net Long Term Debt Issuance,-2558000000.0,-4250000000.0,-3150000000.0,0.0,0.0,NaN
Long Term Debt Payments,-2558000000.0,-4250000000.0,-3150000000.0,0.0,0.0,NaN
Long Term Debt Issuance,0.0,NaN,NaN,NaN,0.0,NaN
Investing Cash Flow,1445000000.0,-127000000.0,-310000000.0,1927000000.0,2394000000.0,NaN
Cash Flow From Continuing Investing Activities,1445000000.0,-127000000.0,-310000000.0,1927000000.0,2394000000.0,NaN
Net Other Investing Changes,-191000000.0,-388000000.0,-445000000.0,-284000000.0,-584000000.0,NaN
Net Investment Purchase And Sale,4544000000.0,2412000000.0,2131000000.0,4603000000.0,5141000000.0,NaN
Sale Of Investment,15126000000.0,15444000000.0,17393000000.0,14383000000.0,13698000000.0,NaN
Purchase Of Investment,-10582000000.0,-13032000000.0,-15262000000.0,-9780000000.0,-8557000000.0,NaN
Net PPE Purchase And Sale,-2908000000.0,-2151000000.0,-1996000000.0,-2392000000.0,-2163000000.0,NaN
Purchase Of PPE,-2908000000.0,-2151000000.0,-1996000000.0,-2392000000.0,-2163000000.0,NaN
Operating Cash Flow,26811000000.0,28858000000.0,22690000000.0,39895000000.0,21598000000.0,NaN
Cash Flow From Continuing Operating Activities,26811000000.0,28858000000.0,22690000000.0,39895000000.0,21598000000.0,NaN
Change In Working Capital,6608000000.0,1684000000.0,-5764000000.0,1123000000.0,-6060000000.0,NaN
Change In Other Current Liabilities,15550000000.0,3439000000.0,428000000.0,-3865000000.0,45000000.0,NaN
Change In Other Current Assets,-6105000000.0,-1188000000.0,-2981000000.0,-1457000000.0,-821000000.0,NaN
Change In Payables And Accrued Expense,21191000000.0,1539000000.0,-12168000000.0,-4542000000.0,14901000000.0,NaN
Change In Payable,21191000000.0,1539000000.0,-12168000000.0,-4542000000.0,14901000000.0,NaN
Change In Account Payable,21191000000.0,1539000000.0,-12168000000.0,-4542000000.0,14901000000.0,NaN
Change In Inventory,-1087000000.0,-12000000.0,190000000.0,-137000000.0,952000000.0,NaN
Change In Receivables,-22941000000.0,-2094000000.0,8767000000.0,11124000000.0,-21137000000.0,NaN
Changes In Account Receivables,-10485000000.0,-1030000000.0,1172000000.0,6555000000.0,-9297000000.0,NaN
Other Non Cash Items,-302000000.0,7000000.0,-982000000.0,-989000000.0,-576000000.0,NaN
Stock Based Compensation,2858000000.0,2869000000.0,2964000000.0,2997000000.0,2625000000.0,NaN
Depreciation Amortization Depletion,2911000000.0,2850000000.0,2836000000.0,2848000000.0,2653000000.0,NaN
Depreciation And Amortization,2911000000.0,2850000000.0,2836000000.0,2848000000.0,2653000000.0,NaN
Net Income From Continuing Operations,14736000000.0,21448000000.0,23636000000.0,33916000000.0,22956000000.0,NaN

#Calling the Dividends

In [6]:
dividends = yf.Ticker("aapl").dividends
dividends

Date
1987-05-11 00:00:00-04:00    0.000536
1987-08-10 00:00:00-04:00    0.000536
1987-11-17 00:00:00-05:00    0.000714
1988-02-12 00:00:00-05:00    0.000714
1988-05-16 00:00:00-04:00    0.000714
                               ...
2023-11-10 00:00:00-05:00    0.240000
2024-02-09 00:00:00-05:00    0.240000
2024-05-10 00:00:00-04:00    0.250000
2024-08-12 00:00:00-04:00    0.250000
2024-11-08 00:00:00-05:00    0.250000
Name: Dividends, Length: 85, dtype: float64

#Calling the SEC filings Yahoo API has and how they are using it
They use AWS

In [7]:
import yfinance as yf

sec_filings_data = yf.Ticker("aapl").sec_filings
sec_filings_data

[{'date': datetime.date(2024, 11, 1),
  'epochDate': 1730419200,
  'type': 'S-3ASR',
  'title': 'Offering Registrations',
  'edgarUrl': 'https://finance.yahoo.com/sec-filing/AAPL/0001140361-24-044880_320193',
  'exhibits': {'S-3ASR': 'https://cdn.yahoofinance.com/prod/sec-filings/0000320193/000114036124044880/ny20033611x4_s3asr.htm',
   'EXCEL': 'https://s3.amazonaws.com/finance-pri-uw2/sec-filings/0000320193/000114036124044880/Financial_Report.xlsx',
   'EX-23.2': 'https://cdn.yahoofinance.com/prod/sec-filings/0000320193/000114036124044880/ny20033611x4_ex23-2.htm',
   'EX-25.1': 'https://cdn.yahoofinance.com/prod/sec-filings/0000320193/000114036124044880/ny20033611x4_ex25-1.htm',
   'EX-4.1': 'https://cdn.yahoofinance.com/prod/sec-filings/0000320193/000114036124044880/ny20033611x4_ex4-1.htm',
   'EX-5.1': 'https://cdn.yahoofinance.com/prod/sec-filings/0000320193/000114036124044880/ny20033611x4_ex5-1.htm',
   'EX-FILING FEES': 'https://cdn.yahoofinance.com/prod/sec-filings/0000320193/000114036124044880/ny20033611x4_exfilings.htm'},
  'maxAge': 1},
 {'date': datetime.date(2024, 10, 31),
  'epochDate': 1730332800,
  'type': '8-K',
  'title': 'Corporate Changes & Voting Matters',
  'edgarUrl': 'https://finance.yahoo.com/sec-filing/AAPL/0000320193-24-000120_320193',
  'exhibits': {'8-K': 'https://cdn.yahoofinance.com/prod/sec-filings/0000320193/000032019324000120/aapl-20241031.htm',
   'EX-99.1': 'https://cdn.yahoofinance.com/prod/sec-filings/0000320193/000032019324000120/a8-kex991q4202409282024.htm',
   'EXCEL': 'https://s3.amazonaws.com/finance-pri-uw2/sec-filings/0000320193/000032019324000120/Financial_Report.xlsx'},
  'maxAge': 1},
 {'date': datetime.date(2024, 9, 10),
  'epochDate': 1725926400,
  'type': '8-K',
  'title': 'Corporate Changes & Voting Matters',
  'edgarUrl': 'https://finance.yahoo.com/sec-filing/AAPL/0001140361-24-040659_320193',
  'exhibits': {'8-K': 'https://cdn.yahoofinance.com/prod/sec-filings/0000320193/000114036124040659/ef20035718_8k.htm',
   'EXCEL': 'https://s3.amazonaws.com/finance-pri-uw2/sec-filings/0000320193/000114036124040659/Financial_Report.xlsx'},
  'maxAge': 1},
 {'date': datetime.date(2024, 8, 26),
  'epochDate': 1724630400,
  'type': '8-K',
  'title': 'Corporate Changes & Voting Matters',
  'edgarUrl': 'https://finance.yahoo.com/sec-filing/AAPL/0001140361-24-038601_320193',
  'exhibits': {'EXCEL': 'https://s3.amazonaws.com/finance-pri-uw2/sec-filings/0000320193/000114036124038601/Financial_Report.xlsx',
   '8-K': 'https://cdn.yahoofinance.com/prod/sec-filings/0000320193/000114036124038601/ny20033611x3_8k.htm'},
  'maxAge': 1},
 {'date': datetime.date(2024, 8, 23),
  'epochDate': 1724371200,
  'type': '8-K',
  'title': 'Corporate Changes & Voting Matters',
  'edgarUrl': 'https://finance.yahoo.com/sec-filing/AAPL/0001140361-24-038403_320193',
  'exhibits': {'8-K': 'https://cdn.yahoofinance.com/prod/sec-filings/0000320193/000114036124038403/ny20033611x2_8k.htm',
   'EXCEL': 'https://s3.amazonaws.com/finance-pri-uw2/sec-filings/0000320193/000114036124038403/Financial_Report.xlsx',
   'EX-3.2': 'https://cdn.yahoofinance.com/prod/sec-filings/0000320193/000114036124038403/ny20033611x2_ex3-2.htm'},
  'maxAge': 1},
 {'date': datetime.date(2024, 8, 2),
  'epochDate': 1722556800,
  'type': '10-Q',
  'title': 'Periodic Financial Reports',
  'edgarUrl': 'https://finance.yahoo.com/sec-filing/AAPL/0000320193-24-000081_320193',
  'exhibits': {'10-Q': 'https://cdn.yahoofinance.com/prod/sec-filings/0000320193/000032019324000081/aapl-20240629.htm',
   'EX-31.1': 'https://cdn.yahoofinance.com/prod/sec-filings/0000320193/000032019324000081/a10-qexhibit31106292024.htm',
   'EX-31.2': 'https://cdn.yahoofinance.com/prod/sec-filings/0000320193/000032019324000081/a10-qexhibit31206292024.htm',
   'EX-32.1': 'https://cdn.yahoofinance.com/prod/sec-filings/0000320193/000032019324000081/a10-qexhibit32106292024.htm',
   'EXCEL': 'https://s3.amazonaws.com/finance-pri-uw2/sec-filings/0000320193/000032019324000081/Financial_Report.xlsx'},
  'maxAge': 1},
 {'date': datetime.date(2024, 8, 1),
  'epochDate': 1722470400,
  'type': '8-K',
  'title': 'Corporate Changes & Voting Matters',
  'edgarUrl': 'https://finance.yahoo.com/sec-filing/AAPL/0000320193-24-000080_320193',
  'exhibits': {'8-K': 'https://cdn.yahoofinance.com/prod/sec-filings/0000320193/000032019324000080/aapl-20240801.htm',
   'EX-99.1': 'https://cdn.yahoofinance.com/prod/sec-filings/0000320193/000032019324000080/a8-kex991q3202406292024.htm',
   'EXCEL': 'https://s3.amazonaws.com/finance-pri-uw2/sec-filings/0000320193/000032019324000080/Financial_Report.xlsx'},
  'maxAge': 1},
 {'date': datetime.date(2024, 5, 3),
  'epochDate': 1714694400,
  'type': '10-Q',
  'title': 'Periodic Financial Reports',
  'edgarUrl': 'https://finance.yahoo.com/sec-filing/AAPL/0000320193-24-000069_320193',
  'exhibits': {'10-Q': 'https://cdn.yahoofinance.com/prod/sec-filings/0000320193/000032019324000069/aapl-20240330.htm',
   'EX-31.1': 'https://cdn.yahoofinance.com/prod/sec-filings/0000320193/000032019324000069/a10-qexhibit31103302024.htm',
   'EX-31.2': 'https://cdn.yahoofinance.com/prod/sec-filings/0000320193/000032019324000069/a10-qexhibit31203302024.htm',
   'EX-32.1': 'https://cdn.yahoofinance.com/prod/sec-filings/0000320193/000032019324000069/a10-qexhibit32103302024.htm',
   'EXCEL': 'https://s3.amazonaws.com/finance-pri-uw2/sec-filings/0000320193/000032019324000069/Financial_Report.xlsx'},
  'maxAge': 1},
 {'date': datetime.date(2024, 5, 2),
  'epochDate': 1714608000,
  'type': '8-K',
  'title': 'Corporate Changes & Voting Matters',
  'edgarUrl': 'https://finance.yahoo.com/sec-filing/AAPL/0000320193-24-000067_320193',
  'exhibits': {'8-K': 'https://cdn.yahoofinance.com/prod/sec-filings/0000320193/000032019324000067/aapl-20240502.htm',
   'EX-99.1': 'https://cdn.yahoofinance.com/prod/sec-filings/0000320193/000032019324000067/a8-kex991q2202403302024.htm',
   'EXCEL': 'https://s3.amazonaws.com/finance-pri-uw2/sec-filings/0000320193/000032019324000067/Financial_Report.xlsx'},
  'maxAge': 1},
 {'date': datetime.date(2024, 4, 29),
  'epochDate': 1714348800,
  'type': 'CORRESP',
  'title': 'A correspondence can be sent as a document with another submission type or can be sent as a separate submission',
  'edgarUrl': 'https://finance.yahoo.com/sec-filing/AAPL/0000320193-24-000061_320193',
  'exhibits': {'CORRESP': 'https://cdn.yahoofinance.com/prod/sec-filings/0000320193/000032019324000061/filename1.htm'},
  'maxAge': 1},
 {'date': datetime.date(2024, 4, 5),
  'epochDate': 1712275200,
  'type': 'CORRESP',
  'title': 'A correspondence can be sent as a document with another submission type or can be sent as a separate submission',
  'edgarUrl': 'https://finance.yahoo.com/sec-filing/AAPL/0001140361-24-018378_320193',
  'exhibits': {'CORRESP': 'https://cdn.yahoofinance.com/prod/sec-filings/0000320193/000114036124018378/filename1.htm'},
  'maxAge': 1},
 {'date': datetime.date(2024, 3, 27),
  'epochDate': 1711497600,
  'type': 'SD',
  'title': 'Specialized Disclosure Report filed pursuant to Section 1502 of the Dodd-Frank Wall Street Reform and Consumer Protection Act relating to the use of conflict minerals (Rule 13p-1)',
  'edgarUrl': 'https://finance.yahoo.com/sec-filing/AAPL/0001140361-24-015633_320193',
  'exhibits': {'SD': 'https://cdn.yahoofinance.com/prod/sec-filings/0000320193/000114036124015633/ef20024616_sd.htm',
   'EX-1.01': 'https://cdn.yahoofinance.com/prod/sec-filings/0000320193/000114036124015633/ef20024616_ex1-01.htm'},
  'maxAge': 1},
 {'date': datetime.date(2024, 3, 20),
  'epochDate': 1710892800,
  'type': 'CORRESP',
  'title': 'A correspondence can be sent as a document with another submission type or can be sent as a separate submission',
  'edgarUrl': 'https://finance.yahoo.com/sec-filing/AAPL/0000320193-24-000042_320193',
  'exhibits': {'CORRESP': 'https://cdn.yahoofinance.com/prod/sec-filings/0000320193/000032019324000042/filename1.htm'},
  'maxAge': 1},
 {'date': datetime.date(2024, 2, 28),
  'epochDate': 1709078400,
  'type': '8-K',
  'title': 'Corporate Changes & Voting Matters',
  'edgarUrl': 'https://finance.yahoo.com/sec-filing/AAPL/0001140361-24-010155_320193',
  'exhibits': {'EXCEL': 'https://s3.amazonaws.com/finance-pri-uw2/sec-filings/0000320193/000114036124010155/Financial_Report.xlsx',
   '8-K': 'https://cdn.yahoofinance.com/prod/sec-filings/0000320193/000114036124010155/ny20022580x1_8k.htm'},
  'maxAge': 1},
 {'date': datetime.date(2024, 2, 14),
  'epochDate': 1707868800,
  'type': 'SC 13G/A',
  'title': 'Tender Offer/Acquisition Reports',
  'edgarUrl': 'https://finance.yahoo.com/sec-filing/AAPL/0001193125-24-036431_320193',
  'exhibits': {'SC 13G/A': 'https://cdn.yahoofinance.com/prod/sec-filings/0001067983/000119312524036431/d751537dsc13ga.htm',
   'EX-99.A': 'https://cdn.yahoofinance.com/prod/sec-filings/0001067983/000119312524036431/d751537dex99a.htm',
   'EX-99.B': 'https://cdn.yahoofinance.com/prod/sec-filings/0001067983/000119312524036431/d751537dex99b.htm'},
  'maxAge': 1},
 {'date': datetime.date(2024, 2, 12),
  'epochDate': 1707696000,
  'type': 'SC 13G/A',
  'title': 'Tender Offer/Acquisition Reports',
  'edgarUrl': 'https://finance.yahoo.com/sec-filing/AAPL/0001086364-24-006980_320193',
  'exhibits': {},
  'maxAge': 1},
 {'date': datetime.date(2024, 2, 2),
  'epochDate': 1706832000,
  'type': '10-Q',
  'title': 'Periodic Financial Reports',
  'edgarUrl': 'https://finance.yahoo.com/sec-filing/AAPL/0000320193-24-000006_320193',
  'exhibits': {'10-Q': 'https://cdn.yahoofinance.com/prod/sec-filings/0000320193/000032019324000006/aapl-20231230.htm',
   'EX-31.1': 'https://cdn.yahoofinance.com/prod/sec-filings/0000320193/000032019324000006/a10-qexhibit31112302023.htm',
   'EX-31.2': 'https://cdn.yahoofinance.com/prod/sec-filings/0000320193/000032019324000006/a10-qexhibit31212302023.htm',
   'EX-32.1': 'https://cdn.yahoofinance.com/prod/sec-filings/0000320193/000032019324000006/a10-qexhibit32112302023.htm',
   'EXCEL': 'https://s3.amazonaws.com/finance-pri-uw2/sec-filings/0000320193/000032019324000006/Financial_Report.xlsx'},
  'maxAge': 1},
 {'date': datetime.date(2024, 2, 1),
  'epochDate': 1706745600,
  'type': '8-K',
  'title': 'Corporate Changes & Voting Matters',
  'edgarUrl': 'https://finance.yahoo.com/sec-filing/AAPL/0000320193-24-000005_320193',
  'exhibits': {'8-K': 'https://cdn.yahoofinance.com/prod/sec-filings/0000320193/000032019324000005/aapl-20240201.htm',
   'EX-99.1': 'https://cdn.yahoofinance.com/prod/sec-filings/0000320193/000032019324000005/a8-kex991q1202412302023.htm',
   'EXCEL': 'https://s3.amazonaws.com/finance-pri-uw2/sec-filings/0000320193/000032019324000005/Financial_Report.xlsx'},
  'maxAge': 1},
 {'date': datetime.date(2024, 1, 11),
  'epochDate': 1704931200,
  'type': 'DEFA14A',
  'title': 'Proxy Statements',
  'edgarUrl': 'https://finance.yahoo.com/sec-filing/AAPL/0001308179-24-000011_320193',
  'exhibits': {'DEFA14A': 'https://cdn.yahoofinance.com/prod/sec-filings/0000320193/000130817924000011/laapl2024_defa14a.htm'},
  'maxAge': 1},
 {'date': datetime.date(2023, 11, 3),
  'epochDate': 1698969600,
  'type': '10-K',
  'title': 'Periodic Financial Reports',
  'edgarUrl': 'https://finance.yahoo.com/sec-filing/AAPL/0000320193-23-000106_320193',
  'exhibits': {'EX-21.1': 'https://cdn.yahoofinance.com/prod/sec-filings/0000320193/000032019323000106/a10-kexhibit21109302023.htm',
   'EX-23.1': 'https://cdn.yahoofinance.com/prod/sec-filings/0000320193/000032019323000106/a10-kexhibit23109302023.htm',
   'EX-31.1': 'https://cdn.yahoofinance.com/prod/sec-filings/0000320193/000032019323000106/a10-kexhibit31109302023.htm',
   'EX-31.2': 'https://cdn.yahoofinance.com/prod/sec-filings/0000320193/000032019323000106/a10-kexhibit31209302023.htm',
   'EX-32.1': 'https://cdn.yahoofinance.com/prod/sec-filings/0000320193/000032019323000106/a10-kexhibit32109302023.htm',
   'EX-4.1': 'https://cdn.yahoofinance.com/prod/sec-filings/0000320193/000032019323000106/a10-kexhibit4109302023.htm',
   'EXCEL': 'https://s3.amazonaws.com/finance-pri-uw2/sec-filings/0000320193/000032019323000106/Financial_Report.xlsx',
   '10-K': 'https://cdn.yahoofinance.com/prod/sec-filings/0000320193/000032019323000106/aapl-20230930.htm'},
  'maxAge': 1},
 {'date': datetime.date(2023, 11, 2),
  'epochDate': 1698883200,
  'type': '8-K',
  'title': 'Corporate Changes & Voting Matters',
  'edgarUrl': 'https://finance.yahoo.com/sec-filing/AAPL/0000320193-23-000104_320193',
  'exhibits': {'8-K': 'https://cdn.yahoofinance.com/prod/sec-filings/0000320193/000032019323000104/aapl-20231102.htm',
   'EX-99.1': 'https://cdn.yahoofinance.com/prod/sec-filings/0000320193/000032019323000104/a8-kex991q4202309302023.htm',
   'EXCEL': 'https://s3.amazonaws.com/finance-pri-uw2/sec-filings/0000320193/000032019323000104/Financial_Report.xlsx'},
  'maxAge': 1},
 {'date': datetime.date(2023, 8, 4),
  'epochDate': 1691107200,
  'type': '10-Q',
  'title': 'Periodic Financial Reports',
  'edgarUrl': 'https://finance.yahoo.com/sec-filing/AAPL/0000320193-23-000077_320193',
  'exhibits': {'10-Q': 'https://cdn.yahoofinance.com/prod/sec-filings/0000320193/000032019323000077/aapl-20230701.htm',
   'EX-31.1': 'https://cdn.yahoofinance.com/prod/sec-filings/0000320193/000032019323000077/a10-qexhibit31107012023.htm',
   'EX-31.2': 'https://cdn.yahoofinance.com/prod/sec-filings/0000320193/000032019323000077/a10-qexhibit31207012023.htm',
   'EX-32.1': 'https://cdn.yahoofinance.com/prod/sec-filings/0000320193/000032019323000077/a10-qexhibit32107012023.htm',
   'EXCEL': 'https://s3.amazonaws.com/finance-pri-uw2/sec-filings/0000320193/000032019323000077/Financial_Report.xlsx'},
  'maxAge': 1},
 {'date': datetime.date(2023, 8, 3),
  'epochDate': 1691020800,
  'type': '8-K',
  'title': 'Corporate Changes & Voting Matters',
  'edgarUrl': 'https://finance.yahoo.com/sec-filing/AAPL/0000320193-23-000075_320193',
  'exhibits': {'EX-99.1': 'https://cdn.yahoofinance.com/prod/sec-filings/0000320193/000032019323000075/a8-kex991q3202307012023.htm',
   'EXCEL': 'https://s3.amazonaws.com/finance-pri-uw2/sec-filings/0000320193/000032019323000075/Financial_Report.xlsx',
   '8-K': 'https://cdn.yahoofinance.com/prod/sec-filings/0000320193/000032019323000075/aapl-20230803.htm'},
  'maxAge': 1},
 {'date': datetime.date(2023, 5, 10),
  'epochDate': 1683676800,
  'type': '8-K',
  'title': 'Corporate Changes & Voting Matters',
  'edgarUrl': 'https://finance.yahoo.com/sec-filing/AAPL/0001140361-23-023909_320193',
  'exhibits': {'8-K': 'https://cdn.yahoofinance.com/prod/sec-filings/0000320193/000114036123023909/ny20007635x4_8k.htm',
   'EXCEL': 'https://s3.amazonaws.com/finance-pri-uw2/sec-filings/0000320193/000114036123023909/Financial_Report.xlsx',
   'EX-5.1': 'https://cdn.yahoofinance.com/prod/sec-filings/0000320193/000114036123023909/ny20006735x4_ex5-1.htm',
   'EX-1.1': 'https://cdn.yahoofinance.com/prod/sec-filings/0000320193/000114036123023909/ny20007635x4_ex1-1.htm',
   'EX-4.1': 'https://cdn.yahoofinance.com/prod/sec-filings/0000320193/000114036123023909/ny20007635x4_ex4-1.htm'},
  'maxAge': 1},
 {'date': datetime.date(2023, 5, 5),
  'epochDate': 1683244800,
  'type': '10-Q',
  'title': 'Periodic Financial Reports',
  'edgarUrl': 'https://finance.yahoo.com/sec-filing/AAPL/0000320193-23-000064_320193',
  'exhibits': {'10-Q': 'https://cdn.yahoofinance.com/prod/sec-filings/0000320193/000032019323000064/aapl-20230401.htm',
   'EX-31.1': 'https://cdn.yahoofinance.com/prod/sec-filings/0000320193/000032019323000064/a10-qexhibit31104012023.htm',
   'EX-31.2': 'https://cdn.yahoofinance.com/prod/sec-filings/0000320193/000032019323000064/a10-qexhibit31204012023.htm',
   'EX-32.1': 'https://cdn.yahoofinance.com/prod/sec-filings/0000320193/000032019323000064/a10-qexhibit32104012023.htm',
   'EXCEL': 'https://s3.amazonaws.com/finance-pri-uw2/sec-filings/0000320193/000032019323000064/Financial_Report.xlsx'},
  'maxAge': 1},
 {'date': datetime.date(2023, 5, 4),
  'epochDate': 1683158400,
  'type': '8-K',
  'title': 'Corporate Changes & Voting Matters',
  'edgarUrl': 'https://finance.yahoo.com/sec-filing/AAPL/0000320193-23-000063_320193',
  'exhibits': {'EX-99.1': 'https://cdn.yahoofinance.com/prod/sec-filings/0000320193/000032019323000063/a8-kex991q2202304012023.htm',
   'EXCEL': 'https://s3.amazonaws.com/finance-pri-uw2/sec-filings/0000320193/000032019323000063/Financial_Report.xlsx',
   '8-K': 'https://cdn.yahoofinance.com/prod/sec-filings/0000320193/000032019323000063/aapl-20230504.htm'},
  'maxAge': 1},
 {'date': datetime.date(2023, 3, 16),
  'epochDate': 1678924800,
  'type': 'SD',
  'title': 'Specialized Disclosure Report filed pursuant to Section 1502 of the Dodd-Frank Wall Street Reform and Consumer Protection Act relating to the use of conflict minerals (Rule 13p-1)',
  'edgarUrl': 'https://finance.yahoo.com/sec-filing/AAPL/0001140361-23-012065_320193',
  'exhibits': {'EX-1.01': 'https://cdn.yahoofinance.com/prod/sec-filings/0000320193/000114036123012065/brhc10048434_ex1-01.htm',
   'SD': 'https://cdn.yahoofinance.com/prod/sec-filings/0000320193/000114036123012065/brhc10048434_sd.htm'},
  'maxAge': 1},
 {'date': datetime.date(2023, 3, 10),
  'epochDate': 1678406400,
  'type': '8-K',
  'title': 'Corporate Changes & Voting Matters',
  'edgarUrl': 'https://finance.yahoo.com/sec-filing/AAPL/0001140361-23-011192_320193',
  'exhibits': {'8-K': 'https://cdn.yahoofinance.com/prod/sec-filings/0000320193/000114036123011192/brhc10049413_8k.htm',
   'EXCEL': 'https://s3.amazonaws.com/finance-pri-uw2/sec-filings/0000320193/000114036123011192/Financial_Report.xlsx'},
  'maxAge': 1},
 {'date': datetime.date(2023, 2, 22),
  'epochDate': 1677024000,
  'type': 'PX14A6G',
  'title': 'Notice of exempt solicitation',
  'edgarUrl': 'https://finance.yahoo.com/sec-filing/AAPL/0001214659-23-002862_320193',
  'exhibits': {'PX14A6G': 'https://cdn.yahoofinance.com/prod/sec-filings/0001736547/000121465923002862/f214237px14a6g.htm'},
  'maxAge': 1},
 {'date': datetime.date(2023, 2, 14),
  'epochDate': 1676332800,
  'type': 'PX14A6G',
  'title': 'Notice of exempt solicitation',
  'edgarUrl': 'https://finance.yahoo.com/sec-filing/AAPL/0001096906-23-000372_320193',
  'exhibits': {'PX14A6G': 'https://cdn.yahoofinance.com/prod/sec-filings/0001958085/000109690623000372/nlpc_px14a6g.htm'},
  'maxAge': 1},
 {'date': datetime.date(2023, 2, 9),
  'epochDate': 1675900800,
  'type': 'SC 13G/A',
  'title': 'Tender Offer/Acquisition Reports',
  'edgarUrl': 'https://finance.yahoo.com/sec-filing/AAPL/0001104659-23-015055_320193',
  'exhibits': {'SC 13G/A': 'https://cdn.yahoofinance.com/prod/sec-filings/0000320193/000110465923015055/tv0017-appleinc.htm'},
  'maxAge': 1},
 {'date': datetime.date(2023, 2, 7),
  'epochDate': 1675728000,
  'type': 'SC 13G/A',
  'title': 'Tender Offer/Acquisition Reports',
  'edgarUrl': 'https://finance.yahoo.com/sec-filing/AAPL/0001306550-23-008266_320193',
  'exhibits': {},
  'maxAge': 1},
 {'date': datetime.date(2023, 2, 3),
  'epochDate': 1675382400,
  'type': '10-Q',
  'title': 'Periodic Financial Reports',
  'edgarUrl': 'https://finance.yahoo.com/sec-filing/AAPL/0000320193-23-000006_320193',
  'exhibits': {'EX-10.1': 'https://cdn.yahoofinance.com/prod/sec-filings/0000320193/000032019323000006/a10-qexhibit10112312022.htm',
   'EX-10.2': 'https://cdn.yahoofinance.com/prod/sec-filings/0000320193/000032019323000006/a10-qexhibit10212312022.htm',
   'EX-31.1': 'https://cdn.yahoofinance.com/prod/sec-filings/0000320193/000032019323000006/a10-qexhibit31112312022.htm',
   'EX-31.2': 'https://cdn.yahoofinance.com/prod/sec-filings/0000320193/000032019323000006/a10-qexhibit31212312022.htm',
   'EX-32.1': 'https://cdn.yahoofinance.com/prod/sec-filings/0000320193/000032019323000006/a10-qexhibit32112312022.htm',
   'EXCEL': 'https://s3.amazonaws.com/finance-pri-uw2/sec-filings/0000320193/000032019323000006/Financial_Report.xlsx',
   '10-Q': 'https://cdn.yahoofinance.com/prod/sec-filings/0000320193/000032019323000006/aapl-20221231.htm'},

In [23]:
#Isolating Total Revenue from the Income Statement Yearly
# Access the income statement data as a Pandas DataFrame.
income_statement = yf.Ticker("aapl").income_stmt

# Access 'Total Revenue' using the appropriate index label.
total_revenue = income_statement.loc['Total Revenue']

# Print or use total_revenue.
print(total_revenue)

2024-09-30    391035000000.0
2023-09-30    383285000000.0
2022-09-30    394328000000.0
2021-09-30    365817000000.0
2020-09-30               NaN
Name: Total Revenue, dtype: object

In [24]:
#Transposing the Income Statement
import yfinance as yf

# Get the income statement data
income_statement = yf.Ticker("aapl").income_stmt

# Transpose the DataFrame
rearranged_income_statement = income_statement.transpose()

# Now 'rearranged_income_statement' has dates as rows and line items as columns
print(rearranged_income_statement)

           Tax Effect Of Unusual Items Tax Rate For Calcs Normalized EBITDA  \
2024-09-30                         0.0           0.240912    134661000000.0
2023-09-30                         0.0           0.147192    125820000000.0
2022-09-30                         0.0              0.162    130541000000.0
2021-09-30                         0.0              0.133    123136000000.0
2020-09-30                         NaN                NaN               NaN

           Net Income From Continuing Operation Net Minority Interest  \
2024-09-30                                      93736000000.0
2023-09-30                                      96995000000.0
2022-09-30                                      99803000000.0
2021-09-30                                      94680000000.0
2020-09-30                                                NaN

           Reconciled Depreciation Reconciled Cost Of Revenue          EBITDA  \
2024-09-30           11445000000.0             210352000000.0  134661000000.0
2023-09-30           11519000000.0             214137000000.0  125820000000.0
2022-09-30           11104000000.0             223546000000.0  130541000000.0
2021-09-30           11284000000.0             212981000000.0  123136000000.0
2020-09-30                     NaN                        NaN             NaN

                      EBIT Net Interest Income Interest Expense  ...  \
2024-09-30  123216000000.0                 NaN              NaN  ...
2023-09-30  114301000000.0        -183000000.0     3933000000.0  ...
2022-09-30  119437000000.0        -106000000.0     2931000000.0  ...
2021-09-30  111852000000.0         198000000.0     2645000000.0  ...
2020-09-30             NaN         890000000.0     2873000000.0  ...

           Interest Expense Non Operating Interest Income Non Operating  \
2024-09-30                            NaN                           NaN
2023-09-30                   3933000000.0                  3750000000.0
2022-09-30                   2931000000.0                  2825000000.0
2021-09-30                   2645000000.0                  2843000000.0
2020-09-30                   2873000000.0                  3763000000.0

           Operating Income Operating Expense Research And Development  \
2024-09-30   123216000000.0     57467000000.0            31370000000.0
2023-09-30   114301000000.0     54847000000.0            29915000000.0
2022-09-30   119437000000.0     51345000000.0            26251000000.0
2021-09-30   108949000000.0     43887000000.0            21914000000.0
2020-09-30              NaN               NaN                      NaN

           Selling General And Administration    Gross Profit Cost Of Revenue  \
2024-09-30                      26097000000.0  180683000000.0  210352000000.0
2023-09-30                      24932000000.0  169148000000.0  214137000000.0
2022-09-30                      25094000000.0  170782000000.0  223546000000.0
2021-09-30                      21973000000.0  152836000000.0  212981000000.0
2020-09-30                                NaN             NaN             NaN

             Total Revenue Operating Revenue
2024-09-30  391035000000.0    391035000000.0
2023-09-30  383285000000.0    383285000000.0
2022-09-30  394328000000.0    394328000000.0
2021-09-30  365817000000.0    365817000000.0
2020-09-30             NaN               NaN

[5 rows x 39 columns]